# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Filter the (very large) ICPSR data files to include only the records for a single state
#' @export
#' @param filePaths paths to the files to filter
#' @param state two-letter state code for records to select
#' @param outputDir directory into which filtered files are written
#' @return a named character vector mapping input file paths to output (filtered) file paths
filterICPSRFiles <- function(filePaths, state, outputDir) {
    .Call('_nibrs_filterICPSRFiles', PACKAGE = 'nibrs', filePaths, state, outputDir)
}

