// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// filterICPSRFiles
StringVector filterICPSRFiles(StringVector filePaths, std::string state, std::string outputDir);
RcppExport SEXP _nibrs_filterICPSRFiles(SEXP filePathsSEXP, SEXP stateSEXP, SEXP outputDirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type filePaths(filePathsSEXP);
    Rcpp::traits::input_parameter< std::string >::type state(stateSEXP);
    Rcpp::traits::input_parameter< std::string >::type outputDir(outputDirSEXP);
    rcpp_result_gen = Rcpp::wrap(filterICPSRFiles(filePaths, state, outputDir));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nibrs_filterICPSRFiles", (DL_FUNC) &_nibrs_filterICPSRFiles, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_nibrs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
